default:
    just --list
up:
    docker compose up -d

sh-go:
    docker compose exec go fish

sh-web:
    docker compose exec web fish

sh-db:
    docker compose exec db fish

clean:
    docker compose down -v
    docker builder prune -a -f
    docker image prune -f

docker-clean:
    docker system prune -a -f
